### ISSUE TITLE
License statement

### ISSUE THREAD

**Issue by Ablu** [JavascriptNet/Javascript.Net#29]
Hi,

we are wondering wether we can use this project. Some files seem to have license headers, but we are missing a project level `LICENSE` file. Could you give a statement about the complete licensing of this piece of software?

Regards,
Ablu

**Comment by oliverbock** [comment]
I have copied the license from the old codeplex site into a file called LICENSE.

**Comment by Ablu** [comment]
Thanks a lot for the update. Looks useable for us then :)

**Comment by doublewaterfish** [comment]
Hi,

I notice that the license file is with BSD 3-clause while the license text in source code head is BSD 2-clause, so which one will be applied to this project?

Thanks,

**Comment by oliverbock** [comment]
Thanks for spotting this.  I have switched the LICENSE file to the 2-clause BSD, to match the source files.
