### ISSUE TITLE
 fatal error in v8::context::new

### ISSUE THREAD

**Issue by nekitrulez** [JavascriptNet/Javascript.Net#30]
Hello, Sometimes when I'm using JavaScriptContext in a loop I get the exception "fatal error in v8::context::new". What cause of this problem it could be?

**Comment by oliverbock** [comment]
I would guess that you are not destroying the context.  You could post your code.

**Comment by nekitrulez** [comment]
I'm disposing it. I have a multithread application. Each class executing in his own thread. Some of this classes are using Javascript.net. Here is an example of method, this method is executing in a loop.

private Proxy GetProxyFromJavaScript(string javascript)
        {
            Proxy proxy = null;

            try
            {
                string tmp = javascript.Split(';')[2].Substring(8, javascript.Split(';')[2].Length - 11);

                using (JavascriptContext context = new JavascriptContext())
                {
                    context.SetParameter("Proxy", (string)context.Run(javascript.Split(';')[0]));

                    string executionCode = (string)context.Run(tmp);

                    executionCode = executionCode.Replace("document.write", "");

                    string result = (string)context.Run(executionCode);

                    proxy = new Proxy(result.Split(':')[0], ushort.Parse(result.Split(':')[1]));
                }
            }
            catch
            {
                return null;
            }

            return proxy;
        }

**Comment by oliverbock** [comment]
To operate v8 simultaneously in multiple threads you need to create an Isolate for each thread.

    isolate = v8::Isolate::New();

While using v8 in a thread you must protect calls by putting these in scope.

	v8::Locker v8ThreadLock(isolate);
	v8::Isolate::Scope isolate_scope(isolate);
