### ISSUE TITLE
Tabs or spaces for new code?

### ISSUE THREAD

**Issue by Ablu** [JavascriptNet/Javascript.Net#47]
Hi,

when looking at the code I am not sure how to configure my editor, part of the code is with tabs, part is with spaces.

What do you prefer here? Then I would add an [editor config](https://editorconfig.org/) and format my planned contribution that way.

**Comment by oliverbock** [comment]
Hi Erik,

Personally I prefer spaces, though I don't feel strongly.


  Oliver
