### ISSUE TITLE
Run MathJax in C# using Javascript.Net

### ISSUE THREAD

**Issue by johnwebner** [JavascriptNet/Javascript.Net#56]
Is it possible to run complex JS code like [MathJax](https://www.nuget.org/packages/MathJax/) in C# using Javascript.Net?

**Comment by oliverbock** [comment]
JavaScript.Net doesn't include browser-specific bits of JavaScript (like the DOM).  If the code relies on that then it won't work.  The normal standard JavaScript library (e.g. Math.max()) is present.
