### ISSUE TITLE
Decimal type does not work when it's a property of an object

### ISSUE THREAD

**Issue by kevinsbennett** [JavascriptNet/Javascript.Net#7]
When passing a decimal parameter directly, everything works as it should.  Example:

```
JavascriptContext context = new JavascriptContext();
context.SetParameter("test", new decimal(0.333));
context.Run("test = test * 2");
context.GetParameter("test");  //returns 0.666... all is good
```

But when I pass in an object with a decimal property, and try to use that property, it acts strange.  For example:

```
public class Product
{
    public decimal Price {get; set;}
}

JavascriptContext context = new JavascriptContext();
context.SetParameter("test", new Product(){ Price = new decimal(0.333)});
context.Run("test.Price = test.Price * 2");
context.GetParameter("test");  //returns 0.... not good
```

I noticed that the decimal support was added in version 0.7, which is what I'm using.  Maybe there was an oversight when decimal support was added that didn't extend to decimal properties of objects?

Thanks for the help!
KB

**Comment by oliverbock** [comment]
Fixed.
