### ISSUE TITLE
Question: What will be the best way of implementing a good/real sleep() function?

### ISSUE THREAD

**Issue by npetrovski** [JavascriptNet/Javascript.Net#70]
V8 does not support setTimeout, hence implementing of a sleep() function must be done above V8. 

Calling of any C# method outside the JS context does not pause the interpreter, and the only way of work this around is by using a callback function which makes the code unreadable (especially for simple scripting).

Also using something like this:

```
function sleep(milliseconds) {
    var start = new Date().getTime();
    for (var i = 0; i < 1e7; i++) {
        if ((new Date().getTime() - start) > milliseconds){
            break;
        }
    }
}
```
is a very very bad idea...

Do you think there is a better way of implementing a simple (real) sleep function that will pause the interpreter for a certain amount of milliseconds?

**Comment by krwq** [comment]
I've done something to emulate setTimeout years ago, IIRC what I did was following:
- wherever you execute the code in c# you do something like this (i did that in a loop in my app, if you don't have a loop, you might want to consider having it)

```csharp
InjectSomeJsCodeOnInit();
while (!finishMyApp) {
  RunWhateverYouRunBeforeInJS();
  InjectSomeJsCode();
  Sleep(1); // just to not consume 100% of thread
}
```

the setTimeout implementation was that:
1. in the init part: initialize dictionary (regular js object), initialize variable you use for generating timer ids and create setTimeout func
2. when user sets timeout you create id and assign it a function user wants to inject and the metadata (time when should this be executed)
3. when you run the injectSomeJsCode you check if any of the timers should run and remove it or not from the dictionary (for setInterval you leave it)

not sure if that's the simplest though

**Comment by npetrovski** [comment]
Thank you @krwq . In fact I did a similar workaround by using a System.Timer and JavascriptFunction.Call to callback, but I was wondering if I can somehow temporary suspend the JS execution for a certain amount of time and then resume it (emulate a real sleep() function).

**Comment by npetrovski** [comment]
Here is my solution (not perfect at all):

``` C#
    public class CTimer
    {
        public void Wait(int delay, object callback, object[] args = null)
        {
            if (null == args) args = new object[]{ };

            if (delay > 0 && callback != null && callback is JavascriptFunction)
            {

                Timer t = new Timer(delay);
                t.Elapsed += delegate (Object source, ElapsedEventArgs e)
                {
                    try
                    {
                        ((JavascriptFunction)callback).Call(args);
                    }
                    finally {
                        t.Enabled = false;
                        t.Dispose();
                    }
                };
                t.Enabled = true;
            }
        }
    }
...
jsContext.SetParameter("CTimer", new CTimer());
```

``` JS
// Helper Sleep function
function sleep(delay) {
    return new Promise(resolve => CTimer.Wait(delay, resolve));
}
```

``` JS
// Test sleep
(async function main() {
	console.log(new Date());
	await sleep(3000); // sleeps for 3 seconds
	console.log(new Date());
})();
```
