### ISSUE TITLE
Does it supports  .net framework 4.6.1 and greater? Does it supports IE?

### ISSUE THREAD

**Issue by hemant-learningforever** [JavascriptNet/Javascript.Net#80]
Does it supports  .net framework 4.6.1 and greater? Does it supports IE?

**Comment by Ablu** [comment]
The question seems to suggest that there is a misunderstanding. The .NET framework  is mostly backwards compatible. 4.6.1+ is covered by that, however you also need to C++/CLI runtime. Also this executes code from .NET (so for example a C# application) and not a browser like IE.
