### ISSUE TITLE
Warnings : Should I be concerned?

### ISSUE THREAD

**Issue by MikeGriffinReborn** [JavascriptNet/Javascript.Net#81]
I get these no matter how I build, it compiles fine, just concerned these warnings might mean something serious as I read your statement about the 0100003F on your main page, I get these? I have VS2017 and the same exact SDK version as your notes suggest. Happens if I build for x32 or x64 or anything else for that matter ...

Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4244	'argument': **conversion from 'double' to 'int', possible loss of data**	

JavaScript.Net	javascriptinterop.cpp	412	
Warning	LNK4248	unresolved typeref token (**0100004E**) for 'v8.internal.Isolate'; image may not run	JavaScript.Net	JavascriptInterop.obj	1	

Warning	LNK4248	unresolved typeref token (**01000038**) for 'v8.internal.Isolate'; image may not run	JavaScript.Net	JavascriptFunction.obj	1	

Warning	LNK4248	unresolved typeref token (**01000042**) for 'v8.internal.Isolate'; image may not run	JavaScript.Net	JavascriptExternal.obj	1	

Warning	LNK4248	unresolved typeref token (**01000041**) for 'v8.internal.Isolate'; image may not run	JavaScript.Net	JavascriptContext.obj	1

**Comment by MikeGriffinReborn** [comment]
Not sure if this helps?

https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4248?view=vs-2019

**Comment by oliverbock** [comment]
Regarding the "unresolved typeref token" warnings, the documentation you
provided says that it might cause a problem for CLR types.
 v8.internal.Isolate is not a CLR type - it is native - so it should be
OK.  The other warning looks easily fixed, but also not likely to cause any
trouble - the values should be in range.

Regards,
  Oliver
