### ISSUE TITLE
Running Javascript.Net in a ASP.NET Web Applications

### ISSUE THREAD

**Issue by Uncreal** [JavascriptNet/Javascript.Net#89]
is it possible to build this project for a ASP.Net Web Application?
I think the problem is dependency on ICU files.
Can any one help me?

**Comment by oliverbock** [comment]
You will need to include all those files in the same directory as the JavaScriptDotNet.dll, but you've probably already tried that.

**Comment by Uncreal** [comment]
Yes i tryed that. I basically copied all the settings from the working console application to new web application but i get a dependency error on  JavaScript.Net.dll. I saw with the Assembly Binding Log Viewer that ASP.Net could not load icuuc.dll and icui18n.dll so i guess thats the problem.

**Comment by oliverbock** [comment]
Did you copy the 64-bit DLLs?  Most servers are running 64 bit.

**Comment by Uncreal** [comment]
Yes i tryed everything. Is it possible to build Javascript.Net as one single dll with everything inside?
Thx for your help.

**Comment by spahnke** [comment]
We use this library in a ASP.NET web application on .NET Framework successfully for a while now. From what we've learned over the years the following things are typically the cause of those errors.

#### IIS has to run in 64 bit mode
Should be self explanatory, this holds for both IIS and IIS Express (make sure to tick the box in the VS settings).

#### Missing Visual C++ Redistributable
You must have the [Visual C++ Redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) package installed on the target machine. This can be checked easily by compiling the included *Fiddling* project (as 64 bit exe) and running that on the target machine.

#### Running into assembly load problems in IIS
IIS/IIS Express attempts to load *every* assembly present in the `bin/` folder, including the unmanaged V8 specific ones. This led to similar errors for us before. We solved that problem by not including the `JavaScript.Net.dll` and other V8 assemblies in the `bin/` folder, but instead deploying those into a sibling folder. You can then use the `AssemblyResolve` callback on the `AppDomain` to resolve `JavaScript.Net.dll` from the sibling folder (see e.g. https://stackoverflow.com/a/5262129). This is typically setup in the `Global.asax.cs`.
```
WebApp
    |--bin
        |--...
    |--V8
        |--JavaScript.Net.dll
        |--icuuc.dll
        |--...
```

Good luck!

**Comment by Uncreal** [comment]
@spahnke Thank you very much! You helped a lot!
