### ISSUE TITLE
Question: fetch/xmlhttprequest/http request OR run a local executable file

### ISSUE THREAD

**Issue by raymond-ong** [JavascriptNet/Javascript.Net#96]
Hello,

Just trying my luck.

I want to send an HTTP request.
Is this feature supported?
Apparently not when I tried "fetch" and "XMLHttpRequest".
It seems like a browser-implemented feature.

Is there any workaround similar to the suggested for ClearScript?
https://stackoverflow.com/questions/53810084/referenceerrorxmlhttprequest-is-not-defined-while-using-clearscriptv8scripteng

-----
The other option for me is to let JavaScript.net run a local executable file.
Is this possible? Due to security risks, it may not be possible though.

Thank you!

**Comment by oliverbock** [comment]
No.  JavaScript.Net is a JavaScript engine, not a browser.  If you want to write methods in C# to implement XMLHttpRequest then you can.

**Comment by raymond-ong** [comment]
OK thank you @oliverbock
